variables:
- group: tfaz-demo
- name: source
  value: sample001/dev/database

trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - sample001/dev/database/*
    exclude:
    - sample001/dev/database/README.md

pool:
  vmImage: 'vs2017-win2016'

steps:
- template: ../../../templates/terraform-steps.yml
  parameters:
    env: dev
    subscription: $(subscription)
    source: $(source)

